### PR TITLE
Move to vscode based build

### PR DESCRIPTION
**Pull request by jborean93**
This removes the Visual Studio stuff (maybe it can be preserved for people wanting to use it) and creates a build process that generates the 2 dlls for Posh-SSH with the required dependencies set.

What will still need to be done if you wish to move forward with something like this

- [ ] Get the tests running
- [ ] Setup CI, probably through GHA to do a basic build and test on a PR
- [ ] Implement pwsh class stub in C# to let the psm1 load properly
- [ ] Make sure the docs build works
- [ ] There's a [reference](https://github.com/darkoperator/Posh-SSH/blob/0d2d31135c018cc1fc7db8bec8c226bf458897ab/Posh-SSH/Posh-SSH.psm1#L5-L8) to forcing the load Renci for Storage Server, need to see if this is still needed
- [ ] Look at Visual Studio (not VSCode) integration, I just took it out for now

The benefits this PR brings:

- Works cross platform, no need to use VSCode to make changes and test out
- Should fix the module loading problem with Newtonsoft.Json (still need to test out)
- Removes binary artifacts from the source repo, git should only contain the code and dlls shouldn't be checked in
- Will hopefully result in CI being added with some basic tests and a build to run

Let me know your thoughts on this approach and whether you wish for me to continue ahead.

### CODE REVIEW

**Comment by MVKozlov** [comment]
During the quick look, I had a few remarks
1. What is the purpose of using `$ImportModule` instead of `Add-Type` ?
2. `SSHRegistryKeyStore` is implemented in powershell, because c# requires Microsoft.Registry, which is absent in linux, and it is only used for upgrading from version 2, so I see no reason to translate it to c#

**Comment by darkoperator** [comment]
On point 3 by @MVKozlov I'm right now a few commits behind the development branch of Renci, as he mentioned bug fixes and also new features.

**Comment by jborean93** [comment]
> What is the purpose of using $ImportModule instead of Add-Type

`Import-Module` does a bit more than `Add-Type`. It will enumerate the classes to find whatever cmdlets have been defined, pre-load dependencies, and finally support the [IModuleAssemblyInitializer](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.imoduleassemblyinitializer?view=powershellsdk-7.0.0) interface and provide a method that runs on module load and unload. I think this is going to be needed based on the Newtonsoft.Json with PowerCli info you've provided now as that complicates matters.

> SSHRegistryKeyStore is implemented in powershell, because c# requires Microsoft.Registry, which is absent in linux, and it is only used for upgrading from version 2, so I see no reason to translate it to c#

The trouble is the psm1 is loading the assembly that provides the interface and pwsh classes are scanned before the code is run. It will fail to find the base class it implements because the assembly hasn't been loaded yet. While it uses the registry which is Windows only it is using it through the PSProvider interface which can be compiled in a dll in a platform independent way, it just can only run on Windows. An alternative may be to define the class in another file but I've always stayed away from pwsh classes because it has really weird loading mechanisms, especially when used inside classes and from other files.

> Renci DLL in storage server is 2016 year version so it doesnt support most of new features, so if it will be loaded instead of bundled, it wil fault on most connections

> VmWare PowerCli also has its own copy of Newtonsoft.Json. And "Add-Type" Posh-SSH was a working workaround to avoid tampering with it. Maybe there is some method to load "any existing" version for this library, because its version is not critical.

Thanks for the information, I'll have to try this out a bit more but essentially I'm thinking about creating an assembly resolver to try and handle these situations better. For the Renci DLL we can certainly have it favour the version Posh-SSH ships with than the one in the GAC for 2016 storage server. Unfortunately what cannot be done is load the new version on top if the old Renci library has already been loaded in the process. That would be a problem today AFAIK.

One thing I want to check, are you fine with the removal of the Visual Studio code in favour of VSCode an generic ps1 scripts to do the build? Are you fine with using GitHub Actions for CI. I can provide a good template to build the module with PRs and run the basic tests. I can even provide a step to publish the module to the PSGallery when creating a tag starting with `v` which I use for all my modules.

**Comment by MVKozlov** [comment]
So, some more background information and history

- At first there was only the `RequiredAssemblies` setting.
- At this point, PSv7 loaded all DLLs from the specified path, and PSv5.1 loaded the first one found (from powercli)
- after `Add-Type Newtonsoft` this problem was solved
- Some time later, the same solution was implemented for Renci.
- later Newtonsoft was updated to v13
- Now we are here :)

**Comment by MVKozlov** [comment]
by the way, if there is a solution how to use `ConvertFrom-Json` or some other json* from _PowerShellStandard.Library_ directly from the C# class, the need for _Newtonsoft.Json_ will disappear :)
it used only for config reading/writing

**Comment by jborean93** [comment]
> At this point, PSv7 loaded all DLLs from the specified path, and PSv5.1 loaded the first one found (from powercli)

This will still continue to work as long as

* PowerCLI has loaded a version that is the same or newer than what Posh-SSH requires
* If Posh-SSH requires a newer version we can use an assembly loader to try and hack it in an allow it
  * I've got a change locally to enable this

> after Add-Type Newtonsoft this problem was solved

It's not 100% solved, Add-Type will be doing what the autoloading does anyway, it's just more explicitly loading it upfront rather than when the code is actually used.

> Some time later, the same solution was implemented for Renci.

The same thing here can be done about Renci, the only problem is when the actual DLL Windows ships with is loaded beforehand. I'm unsure what is actually using Renci in Storage Server and whether it's used by a component outside of PowerShell. if it is then we can most likely just have it favour the dll Posh-SSH ships with, if it's used by another module in PowerShell this will only work if Posh-SSH is loaded first.

> by the way, if there is a solution how to use ConvertFrom-Json or some other json* from PowerShellStandard.Library directly from the C# class,

The only public way I know how is really a hack and is essentially

```csharp
using PowerShell ps = PowerShell.Create();
ps.AddCommand("ConvertTo-Json").AddParameter("InputObject", obj);
var out ps.Invoke()[0];
```

It will certainly work but it shouldn't be necessary if you load the assemblies properly.

**Pull request closed without merging**
