### PR TITLE
Unified and prettified Operation Progress

### PR DESCRIPTION
**Pull request by MVKozlov**
Common progress bar visualization for **Get/Set-xxxItem**

_WIP_: Is `-NoProgress` switch still needed somewhere ?

Now new progress  bar obey `$ProgressPreference`, so switch is not used

It should be removed or expanded to all mentioned cmdlets. Now it absent in Set-SftpItem

### CODE REVIEW

**Comment by MVKozlov** [comment]
forcepush reason: slightly changed commit messages

**Comment by MVKozlov** [comment]
@darkoperator  what do you think about `$ProgressPreference` vs `-NoProgress` ?

What I should do: - remove _NoProgress_ from cmdlets or support it everywhere ?

**Comment by darkoperator** [comment]
Yeah I think it would be best to remove it and use the standard $prograssPreference. Forgot about that one.

**Comment by MVKozlov** [comment]
I think now it's done

**Comment by darkoperator** [comment]
Thanks :)

**Pull request merged**
