### PR TITLE
Address Issues #49, #50, #55, #56, #57, #59

### PR DESCRIPTION
**Pull request by FireInWinter**
Sorry these are all as one large commit.  I didn't have Git setup while I made a lot of the changes.

Addresses the following Issues:
#49 - Add option to show results from Invoke-SSHCommand as they are generated - Added Invoke-SSHCommandStream
#50 - $Async.IsCompleted in Invoke-SSHCommand missing "-not"
#55 - Invoke-SSHCommand slow to many hosts over slow link
#56 - Invoke-SSHCommand -EnsureConnection throws exception if already connected
#57 - Invoke-SSHCommand will attempt to run against down host
#59 - Get-SSHSession -SessionId 0 Returns all session

### CODE REVIEW

**Comment by darkoperator** [comment]
Arrggg :( this will be a painful one to test and merge

**Comment by FireInWinter** [comment]
Sorry about that.  First time using Git/Github.  Anything I can do to help out?

**Comment by darkoperator** [comment]
No problem, in fact than you for contributing and helping out :)

**Comment by darkoperator** [comment]
Having problems with the Invoke-SSHCommandStream function
<pre>
PS C:\Users\Carlos Perez> Invoke-SSHCommandStream -Command "ping -c 20 8.8.8.8" -SessionId 0
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=45 time=65.1 ms
PS C:\Users\Carlos Perez>
</pre>

I believe it is to problems with the stream in the Renci Libray since it never tells you when new data is available unless you read and check size. I know it also has other issues they have not fixed. 

Also do not see any entry for it in the MAML XML help file for it.

**Comment by darkoperator** [comment]
since a branch was not created for the pull request it includes other commits like the one that splits the output from a string in to a array. This would break scripts for existing users  and I can not merge it with this
<pre>
+                            Output = $Output -replace '\n$' -split '\n'
</pre>

**Comment by darkoperator** [comment]
Some changes include new parameter the XML Help should be updated to reflect this changes.

**Comment by FireInWinter** [comment]
Sorry about not branching it for the pull request.  If you want you can cancel this one and I'll modify some of the things you mentioned and branch it this time before I put in a pull request.

I've never used XML help with PowerShell and am not sure if there are any tools to help write/maintain it.  Do you use anythings specific?

As to the Invoke-SSHCommandStream, I'll probably pull it out of the branch before the next pull request.  I found another problem where it sometimes adds line breaks in the middle of a line.  I'll work on it some more, but it isn't where I thought it was.

With Invoke-SSHCommand, I'll add a switch parameter OutputAsStringArray.  That way if people want it they can have it, but otherwise it will be the same as it was before.

**Comment by darkoperator** [comment]
Just make it in to a comment base help and I will move it in to XML help :)

**Pull request merged**
