### PR TITLE
Added .NET Core version and made key store agnostic to storage

### PR DESCRIPTION
**Pull request by pbrouillet**
Updated Renci.SshNet.dll to latest version.
Refactored the Trusted Keys class into Stores that are agnostic to the underlying storage so that it's not tightly bound to the registry. So far, Memory and Registry have been implemented.

### CODE REVIEW

**Comment by pbrouillet** [comment]
Hi @darkoperator ,

First, thanks for your module, it really helped me complete a project of mine!
However, like some other people in the Issues list, I suffered from the storage of trusted keys into the registry.

In my case, I needed to use the module inside an Azure Function for a scheduled SFTP upload. So, .NET Core and no registry :).

First, I updated a bit your module to have a .NET Core project on the side, that basically reference by links every .cs file from the main project (could have tried multi targetting, I know...).
Then, I made a quick IStore interface, an in-memory implementation and refactored your registry storage into its own IStore implementation.
Finally, created a few cmdlets to instantiate the stores and modified the classes that required registry storage so that they could receive the stores by parameter (-Store $storage).

So far, works fine for an Azure Function.
I also tested it in Linux and PS 5.

**Comment by darkoperator** [comment]
Awesome! Really appreciate the contribution, Will have to learn to build it and will test it. Could make this the base for version 3.x. No clue what an IStore is. I had the idea for version 3.x to have the fingerprints to host in a JSON file on disk or to have the user pass it as a parameter -Fingerprint <string>

**Comment by pbrouillet** [comment]
Actually, IStore was just an abstraction layer I improvised.
It just has GetKeys and SetKey and returns an IDictionary<string, string> so that the underlying storage of keys could be whatever was needed by the current host.

A Json storage could be like this:

class JsonStore : IStore
{
         FileStream _file; // Handle to file

        public IDictionary<string, string> GetKeys()
        {
            var hostKeys = // Read and deserialize files from disk
            return hostKeys;
        }

        public bool SetKey(string host, string fingerprint)
        {
            // Set or update key to disk
            return true;
        }
}

with its associated cmdlet that could have a signature like this:
$store = New-JsonStore -LiteralPath trustedKeys.json

**Comment by darkoperator** [comment]
What is the platform in Azure? This is how I check and set configs in Core projects

**Comment by pbrouillet** [comment]
I'm not sure what you mean but for Azure Functions, it's PowerShell 7.0 in x64.
But if you mean to write the data on the file system of the app service running the Function, it is discouraged (if done in the wrong location, it'll either recycle the pool or be in a volatile location).

In a cloud environment, it'd be better to store the data in a scalable storage like an Azure Table, blob, SQL or Redis.
On-prem, it's overkill and, true, a simple JSON in a secure place would be more than enough.

**Comment by darkoperator** [comment]
When you do $psversiontable.platform what does it return?

**Comment by pbrouillet** [comment]
It returns Win32NT

**Comment by darkoperator** [comment]
moved it to a branch as I learn how it works and populate the Markdown files with description and examples

**Comment by darkoperator** [comment]
Been getting this error, any clue?

```
PS C:\Users\admin> Import-Module C:\Users\admin\Documents\GitHub\Posh-SSH\Source\PoshSSH\PoshSSH.Core\bin\Release\netstandard2.0\PoshSSH.dll -Verbose
VERBOSE: Loading module from path 'C:\Users\admin\Documents\GitHub\Posh-SSH\Source\PoshSSH\PoshSSH.Core\bin\Release\netstandard2.0\PoshSSH.dll'.
VERBOSE: Importing cmdlet 'Get-SCPFile'.
VERBOSE: Importing cmdlet 'Get-SCPFolder'.
VERBOSE: Importing cmdlet 'Get-SCPItem'.
VERBOSE: Importing cmdlet 'Get-SFTPFile'.
VERBOSE: Importing cmdlet 'Get-SFTPItem'.
VERBOSE: Importing cmdlet 'New-SFTPSession'.
VERBOSE: Importing cmdlet 'New-SSHSession'.
VERBOSE: Importing cmdlet 'Set-SCPFile'.
VERBOSE: Importing cmdlet 'Set-SCPFolder'.
VERBOSE: Importing cmdlet 'Set-SCPItem'.
VERBOSE: Importing cmdlet 'Set-SFTPFile'.
VERBOSE: Importing cmdlet 'Set-SFTPFolder'.
VERBOSE: Importing cmdlet 'Set-SFTPItem'.
VERBOSE: Importing cmdlet 'New-SSHMemoryStore'.
VERBOSE: Importing cmdlet 'New-SSHRegistryStore'.
PS C:\Users\admin> New-SSHSession -ComputerName 192.168.1.118 -Credential pi -force

PowerShell credential request
Enter your credentials.
Password for user pi: *********

New-SSHSession: Could not load file or assembly 'SshNet.Security.Cryptography, Version=1.3.0.0, Culture=neutral, PublicKeyToken=2fa9220ff3eadda4'. The system cannot find the file specified.
```

**Comment by pbrouillet** [comment]
It's a dependency of SSH.NET ([https://www.nuget.org/packages/SSH.NET/](https://www.nuget.org/packages/SSH.NET/)) as I updated the nuget to the latest version and set it to .NET Standard.
It needed no dependency for .NET Framework 4 but it does for .NET Standard.

Can you ensure you have this DLL in the \bin output DLLs and that it's reachable from the psd1 reference import?

**Pull request merged**
