### PR TITLE
Improve VerbosePreference and Verbose switch behavior.

### LINKED ISSUE #503: If the VerbosePreference set as string, New-SSHConnection throws InvalidCastException.
In a script, I set the value to `$VerbosePreference` variable as string and run `New-SSHConnection` command. 
The script ends with InvalidCastException.

## Steps to Reproduce
This is a sample script.
```PowerShell
# test.ps1
$VerbosePreference = 'Continue'
$Credential = (Get-Credential)
$SSHHost = 'localhost'
$Session = New-SSHSession -ComputerName $SSHHost -Credential $Credential
```

This script ends with below error.
```PowerShel
PS F:\> .\test.ps1
New-SSHSession : Unable to cast object of type 'System.String' to type 'System.Management.Automation.ActionPreference'.
At F:\test.ps1:5 char:12
+ $Session = New-SSHSession -ComputerName $SSHHost -Credential $Credent …
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [New-SSHSession], InvalidCastException
+ FullyQualifiedErrorId : System.InvalidCastException,SSH.NewSshSession
```

## Environment
```PowerShell
PS F:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS F:\> Get-Module Posh-SSH

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Manifest   3.0.8                 Posh-SSH                            {Get-SCPItem, Get-SFTPItem, Get-SSHHostKey, Get-SSHJs…
```

### Method 1. Set VerbosePrefenrece as ActionPreference
```PowerShell
$VerbosePreference = [System.Management.Automation.ActionPreference]::Continue
```

### Method 2. Specify scope of VerbosePreference as Global
```PowerShell
$Global:VerbosePreference = 'Continue'
```

### PR DESCRIPTION
**Pull request by mkht**
This PR will fix #503

### CODE REVIEW

**Comment by MVKozlov** [comment]
Have you tested the functionality of this code?

The code is written this way because `WriteVerbose()` can't be called from an event handler
```
System.Management.Automation.PSInvalidOperationException:
'The WriteObject and WriteError methods cannot be called from outside the overrides of the BeginProcessing,
 ProcessRecord, and EndProcessing methods, and they can only be called from within the same thread.
Validate that the cmdlet makes these calls correctly, or contact Microsoft Customer Support Services.'
```
btw, #503 - is not `Posh-SSH` error

**Comment by mkht** [comment]
I ran the build on my computer and did some simple tests to make sure it worked, but now that I do it again, I'm having the exact problem you describe.
I may have loaded the wrong module when I ran the test.
will fix the code again. sorry.

By the way, how is not a Posh-SSH error?

**Comment by darkoperator** [comment]
Because since it is an event it is being ran in PSHost and not under the context of the moduleSent from my iPhoneOn Dec 13, 2022, at 10:31 AM, mkht ***@***.***> wrote:﻿
I ran the build on my computer and did some simple tests to make sure it worked, but now that I do it again, I'm having the exact problem you describe.
I may have loaded the wrong module when I ran the test.
will fix the code again. sorry.
By the way, how is not a Posh-SSH error?

**Comment by mkht** [comment]
I have modified the code once again.
Tested with PowerShell 7.3.0, 7.2.7, and 5.1 on Windows.

The code used for the test looks like this.

```PowerShell
$currentGlobalVp = $global:VerbosePreference

$Credential = (Get-Credential)
$Server = '127.0.0.1'

echo "TestCase1. scope:local, type:string, value:contINUe"
# verbose message should be displayed.
$local:VerbosePreference = 'contINUe'
$Session = New-SSHSession -ComputerName $Server -Credential $Credential -AcceptKey
Invoke-SSHCommand -Command 'echo hello' -SSHSession $Session
$Session | Remove-SSHSession
Remove-Variable -Name VerbosePreference -Scope Local

echo "TestCase2. scope:local, type:string, value:SilentlyContinue"
# verbose message should NOT be displayed.
$local:VerbosePreference = 'SilentlyContinue'
$Session = New-SSHSession -ComputerName $Server -Credential $Credential -AcceptKey
Invoke-SSHCommand -Command 'echo hello' -SSHSession $Session
$Session | Remove-SSHSession
Remove-Variable -Name VerbosePreference -Scope Local

echo "TestCase3. scope:local, type:ActionPreference, value:Continue"
# verbose message should be displayed.
$local:VerbosePreference = [System.Management.Automation.ActionPreference]::Continue
$Session = New-SSHSession -ComputerName $Server -Credential $Credential -AcceptKey
Invoke-SSHCommand -Command 'echo hello' -SSHSession $Session
$Session | Remove-SSHSession
Remove-Variable -Name VerbosePreference -Scope Local

echo "TestCase4. scope:local, type:bool, value:true"
# verbose message should NOT be displayed.
$local:VerbosePreference = $true
$Session = New-SSHSession -ComputerName $Server -Credential $Credential -AcceptKey
Invoke-SSHCommand -Command 'echo hello' -SSHSession $Session
$Session | Remove-SSHSession
Remove-Variable -Name VerbosePreference -Scope Local

echo "TestCase5. scope:global, type:ActionPreference, value:Continue"
# verbose message should be displayed.
$global:VerbosePreference = [System.Management.Automation.ActionPreference]::Continue
$Session = New-SSHSession -ComputerName $Server -Credential $Credential -AcceptKey
Invoke-SSHCommand -Command 'echo hello' -SSHSession $Session
$Session | Remove-SSHSession
$global:VerbosePreference = $currentGlobalVp

```

**Comment by MVKozlov** [comment]
> By the way, how is not a Posh-SSH error?

Because of https://github.com/PowerShell/PowerShell/issues/18776 :)

You try to bypass the limitation in the operation of variables in powershell. This has nothing to do with the operation of the module and will manifest itself not only in this module.

If you really need to have `$VerbosePreference` in your script why not use `$global:` or the strongly typed version, it's a script and it's okay to have one core level `$global` in it.

**Comment by MVKozlov** [comment]
I looked at the `WriteVerbose()` implementation in Powershell itself, almost the same method is used there.

[WriteVerbose](https://github.com/PowerShell/PowerShell/blob/9d0bac5addf3e9791331c96a3d96191b31d5c662/src/System.Management.Automation/engine/MshCommandRuntime.cs#L574)
[VerbosePreference](https://github.com/PowerShell/PowerShell/blob/9d0bac5addf3e9791331c96a3d96191b31d5c662/src/System.Management.Automation/engine/MshCommandRuntime.cs#L3093)
[GetEnumPreference](https://github.com/PowerShell/PowerShell/blob/9d0bac5addf3e9791331c96a3d96191b31d5c662/src/System.Management.Automation/engine/ExecutionContext.cs#L522)

So if we can't solve it via `WriteVerbose()`, this option might be acceptable I guess.
But perhaps it would be worth moving it to some separate place and parametrize a bit so that it can be used in other cmdlets. may be for `ProgressPreference`

**Pull request merged**
