### PR TITLE
Enhancement for #99: Private Key File from Memory and Refactoring

### PR DESCRIPTION
**Pull request by splumhoff**
- Enhancement for #99: Private Key File can now also be in Memory.
Example: 
`$key = Get-Content c:\MyPrivateKey.key`
`New-SFTPSession -HostName MyHost -Cred (Get-Credential) -KeyFile $key`
- Refactor of NewSftp and NewSSH: Merged to one Base Class to omit Redundancy 

First commit on GitHub, hope I made it correct. ;)

### CODE REVIEW

**Comment by darkoperator** [comment]
Will test it this weekend

**Comment by MVKozlov** [comment]
-Session work fine, but help still states that `[-KeyFile [<String>]]` ???
and set of -SCP comands still need to support keydata as array

**Comment by darkoperator** [comment]
This feature will be on 2.0, doing a major refactor where I will drop PSv2 add port forwarding and deprecate several cmdlets

**Comment by darkoperator** [comment]
As I do more testing and some early builds to some friends, I think based on feedback it would be better to make it in to a separate parameter set and KeyFile is only a key on disk and have another called Key for the key string array

**Comment by MVKozlov** [comment]
great!
btw, `ConnectionInfoGenerator.cs` doesn't  have FileStream disposing code

**Pull request merged**
