### PR TITLE
Accept host key property for Get-SCPFile and Set-SCPFile

### PR DESCRIPTION
**Pull request by sascha-andres**
I had the requirement to automatically upload an authorized keys file for further handling of deployments. Thewrefore I added the AcceptKey property to those commandlets as well

### CODE REVIEW

**Comment by darkoperator** [comment]
Already made all of this changes for the next release :) the code for the next release is in this branch https://github.com/darkoperator/Posh-SSH/tree/Release_0.4

**Comment by sascha-andres** [comment]
So no need ;)

**Comment by paulomorgado** [comment]
Why isn't `AcceptKey` a `switch` instead of a `bool`?

**Comment by darkoperator** [comment]
Good question, I think I will make the changes for the release tomorrow, after all it will already bream most script since it is a full re-write with changes in how parameters work and are named.

**Comment by paulomorgado** [comment]
I found about this module on http://www.powershellmagazine.com/ and was glad to find it on PSGallery and installed it via Ps-Get.

If you are making those changes, you should probably change to major version (1.6 -> 2.0).

**Comment by darkoperator** [comment]
For 2.0 that is next I have even more chsbges, this is a middle ground. Re
- wrote it for performance, best practices and set the tone for what will
be 2.0

**Pull request closed without merging**
